version: '3.9'

services:
    postgres:
        image: postgres
        container_name: news
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_DOCKER_PORT}'
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - newsly_data:/var/lib/postgresql/data

    nestjs:
        build: .
        command: yarn dev
        volumes:
            - .:/app
        ports:
            - ${PORT}:${PORT_DOCKER}
        depends_on:
            - postgres
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}:${POSTGRES_DOCKER_PORT}
            POSTGRES_DB: ${POSTGRES_DB}
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - postgres
    # pgadmin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     ports:
    #         - 5050:80
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #     depends_on:
    #         - postgres
    #     volumes:
    #         - pgadmin:/var/lib/pgadmin
volumes:
    newsly_data:
    pgadmin:
